name = "SSDC_PRIMA"
uuid = "0a7d04aa-8ac2-47b3-b7a7-9dbd6ad661ed"
version = "0.2.3"
authors = ["Éric Thiébaut <eric.thiebaut@univ-lyon1.fr> and contributors"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
SSDC_PRIMA_jll = "8e902b83-7c50-5151-970b-bd6ceca8bed7"
TypeUtils = "c3b1956e-8857-4d84-9b79-890df85b1e67"

[sources]
SSDC_PRIMA_jll = {path = "/Users/granthec/.julia/dev/SSDC_PRIMA_jll"}

[compat]
Requires = "1"
SSDC_PRIMA_jll = "0.7.2"
TypeUtils = "0.3, 1"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
